# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

target "testTarget" do
  pod 'AFNetworking', '~> 2.5'
  pod 'AFNetworkActivityLogger'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'PSTAlertController'
  pod 'GRMustache', '~> 7.3'
  pod 'FCModel', '~> 0.9'
  pod 'SDWebImage', '~>3.6'
  pod 'UIActivityIndicator-for-SDWebImage'
  pod 'youtube-ios-player-helper', '~> 0.1.1'
  pod 'RETableViewManager', '~> 1.6'
end

